import { StyleSheet } from 'react-native';
import { SCREEN_HEIGHT, SCREEN_WIDTH } from './feedConstants';

/** Screen: VibeFeedScreen (Liste, Filter, Banner, Empty) */
export const vibeFeedScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  newPostsBanner: {
    position: 'absolute',
    alignSelf: 'center',
    zIndex: 30,
  },
  newPostsBannerInner: {
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#22D3EE',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  newPostsBlur: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(34,211,238,0.3)',
    overflow: 'hidden',
  },
  newPostsDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#22D3EE',
  },
  newPostsText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  newPostsArrow: {
    color: '#22D3EE',
    fontSize: 14,
    fontWeight: '800',
  },
  emptyTag: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 5,
    gap: 12,
    paddingHorizontal: 40,
  },
  emptyTagTitle: { color: '#FFFFFF', fontSize: 20, fontWeight: '800', textAlign: 'center' },
  emptyTagSub: { color: 'rgba(255,255,255,0.4)', fontSize: 14, textAlign: 'center', lineHeight: 20 },
  emptyTagBtn: {
    marginTop: 4,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(34,211,238,0.4)',
    backgroundColor: 'rgba(34,211,238,0.1)',
  },
  emptyTagBtnText: { color: '#22D3EE', fontSize: 14, fontWeight: '600' },
  list: {
    flex: 1,
  },
  pageLoadingFooter: {
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 20,
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 8,
  },
  filterScroll: {
    flex: 1,
  },
  filterExploreBtn: {
    borderRadius: 18,
    overflow: 'hidden',
    marginLeft: 2,
  },
  filterExploreBtnBlur: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.12)',
  },
});

/** Einzelner Feed-Post inkl. Action-Buttons */
export const feedItemStyles = StyleSheet.create({
  feedItem: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
    backgroundColor: '#0A0A0A',
    overflow: 'hidden',
    justifyContent: 'flex-end',
  },
  patternOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    padding: 20,
    pointerEvents: 'none',
  },
  bigEmoji: {
    fontSize: 36,
    lineHeight: 48,
    color: '#FFFFFF',
    letterSpacing: 12,
  },
  muteBtn: {
    position: 'absolute',
    bottom: 56,     // über dem Fortschrittsbalken
    right: 14,
    borderRadius: 20,
    overflow: 'hidden',
    zIndex: 20,
  },
  muteBtnInner: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0,0,0,0.52)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  pauseIconWrap: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  } as object,
  doubleTapHeart: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  } as object,
  progressTrack: {
    height: 2,
    backgroundColor: 'rgba(255,255,255,0.25)',
    borderRadius: 1,
    marginTop: 12,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#22D3EE',
    borderRadius: 1,
  },
  tagBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    marginBottom: 8,
  },
  tagDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  tagText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  rightActions: {
    position: 'absolute',
    right: 6,
    bottom: 90,
    gap: 0,
    alignItems: 'center',
  },
  actionBtn: {
    alignItems: 'center',
    marginBottom: 6,
  },
  actionBtnInner: {
    width: 48,
    height: 44,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionCount: {
    color: '#E5E7EB',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  bottomInfo: {
    paddingHorizontal: 20,
    paddingBottom: 110,
    paddingTop: 10,
  },
  authorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    marginBottom: 6,
  },
  authorAvatarWrap: {
    position: 'relative',
  },
  storyRingGradient: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
  },
  storyRingViewed: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: 'rgba(255,255,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  storyRingGap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#050508',
    alignItems: 'center',
    justifyContent: 'center',
  },
  authorAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.4)',
  },
  authorAvatarFallback: {
    backgroundColor: 'rgba(34,211,238,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  authorAvatarInitial: {
    fontSize: 13,
    fontWeight: '700',
    color: '#22D3EE',
  },
  followBadge: {
    position: 'absolute',
    bottom: -4,
    right: -4,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#a78bfa',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#000',
  },
  followBadgeActive: {
    backgroundColor: '#4ade80',
  },
  followBadgePlus: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 15,
  },
  authorName: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  authorTags: {
    color: 'rgba(255,255,255,0.35)',
    fontSize: 10,
    fontWeight: '500',
    letterSpacing: 0.2,
    marginTop: 1,
  },
  caption: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '400',
    maxWidth: '86%',
  },
  captionBlock: {
    marginTop: 4,
    gap: 5,
    maxWidth: '86%',
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
});

export const postShareModalStyles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.65)', justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: '#111118',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingBottom: 34,
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignSelf: 'center',
    marginBottom: 14,
  },
  sectionLabel: { color: '#fff', fontSize: 15, fontWeight: '700', paddingHorizontal: 18, marginBottom: 10 },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: 'rgba(255,255,255,0.1)',
    marginVertical: 14,
    marginHorizontal: 18,
  },

  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginHorizontal: 18,
    marginBottom: 12,
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  searchInput: { flex: 1, color: '#fff', fontSize: 13 },
  userScroll: { marginBottom: 4 },
  userScrollContent: { paddingHorizontal: 14, gap: 6 },
  userItem: { alignItems: 'center', width: 66, gap: 5 },
  userAvatarWrap: { position: 'relative' },
  userAvatarChosen: {},
  userAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  userAvatarFallback: {
    backgroundColor: 'rgba(34,211,238,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userAvatarText: { color: '#22D3EE', fontSize: 20, fontWeight: '700' },
  checkBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#22D3EE',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#111118',
  },
  userLabel: { color: 'rgba(255,255,255,0.7)', fontSize: 11, textAlign: 'center', width: 62 },
  emptyUsers: { color: 'rgba(255,255,255,0.3)', fontSize: 13, paddingHorizontal: 4, paddingVertical: 6 },
  sendBtn: {
    marginHorizontal: 18,
    marginTop: 10,
    backgroundColor: '#22D3EE',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 8,
  },
  sendBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },

  appRow: { paddingHorizontal: 14, gap: 8 },
  appItem: { alignItems: 'center', width: 68, gap: 6 },
  appIcon: { width: 52, height: 52, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  appEmoji: { fontSize: 26 },
  appLabel: { color: 'rgba(255,255,255,0.7)', fontSize: 11, textAlign: 'center' },

  actionRow: { flexDirection: 'row', paddingHorizontal: 18, gap: 10 },
  actionItem: { flex: 1, alignItems: 'center', gap: 6 },
  actionIcon: { width: 52, height: 52, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  actionLabel: { color: 'rgba(255,255,255,0.6)', fontSize: 11, textAlign: 'center' },
});

export const postOptionsModalStyles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: '#111118',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingBottom: 34,
    paddingHorizontal: 16,
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignSelf: 'center',
    marginBottom: 16,
  },
  title: {
    color: 'rgba(255,255,255,0.45)',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 13,
    paddingHorizontal: 4,
    borderRadius: 14,
  },
  iconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textWrap: { flex: 1, gap: 2 },
  rowLabel: { fontSize: 15, fontWeight: '600' },
  rowSub: { color: 'rgba(255,255,255,0.4)', fontSize: 12 },
  cancelBtn: {
    marginTop: 8,
    paddingVertical: 14,
    alignItems: 'center',
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.07)',
  },
  cancelText: { color: 'rgba(255,255,255,0.55)', fontSize: 15, fontWeight: '600' },
});
