import { StyleSheet } from 'react-native';
import { GRID_GAP, GRID_CELL_WIDTH } from './profileConstants';

export const profileStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#000' },
  heroBg: { position: 'absolute', top: 0, left: 0, right: 0 },

  header: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 10,
  },
  studioLabel: {
    color: 'rgba(167,139,250,0.6)',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  handle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: -0.4,
    marginTop: 1,
  },
  headerRight: { flexDirection: 'row', gap: 6 },
  hBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  hBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    minWidth: 13,
    height: 13,
    borderRadius: 7,
    backgroundColor: '#F472B6',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
    borderWidth: 1.5,
    borderColor: '#000',
  },
  hBadgeText: { color: '#fff', fontSize: 7, fontWeight: '800' },

  creatorCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 16,
    gap: 14,
  },

  avatarCol: { alignItems: 'center', gap: 6 },
  avatarRing: { width: 80, height: 80, borderRadius: 40, alignItems: 'center', justifyContent: 'center' },
  avatarGap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    overflow: 'hidden',
    borderWidth: 2.5,
    borderColor: '#000',
  },
  avatarImg: { width: '100%', height: '100%' },
  avatarFallback: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  avatarInitial: { color: '#fff', fontSize: 28, fontWeight: '800' },
  guildBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: 'rgba(52,211,153,0.1)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(52,211,153,0.25)',
  },
  guildBadgePending: { backgroundColor: 'rgba(251,191,36,0.08)', borderColor: 'rgba(251,191,36,0.2)' },
  guildBadgeText: { color: '#34D399', fontSize: 9, fontWeight: '700' },

  bioCol: { flex: 1, gap: 4 },
  displayName: { color: '#fff', fontSize: 15, fontWeight: '700' },
  bio: { color: 'rgba(255,255,255,0.4)', fontSize: 12, lineHeight: 17 },
  followRow: { flexDirection: 'row', alignItems: 'center', marginTop: 5, flexWrap: 'wrap' },
  followNum: { color: 'rgba(255,255,255,0.65)', fontSize: 11, fontWeight: '700' },
  followLabel: { color: 'rgba(255,255,255,0.3)', fontSize: 11, fontWeight: '400' },
  followDot: { color: 'rgba(255,255,255,0.2)', fontSize: 11 },
  editPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.09)',
    marginTop: 2,
  },
  editPillText: { color: 'rgba(255,255,255,0.4)', fontSize: 11, fontWeight: '600' },

  scoreCol: { alignItems: 'center', justifyContent: 'center' },

  metricsRow: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.07)',
    overflow: 'hidden',
  },
  metricDivider: {
    width: StyleSheet.hairlineWidth,
    backgroundColor: 'rgba(255,255,255,0.07)',
    marginVertical: 14,
  },
  kachel: { flex: 1, alignItems: 'center', paddingVertical: 14, gap: 4 },
  kachelIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  kachelValue: { color: '#fff', fontSize: 15, fontWeight: '800', letterSpacing: -0.3 },
  kachelLabel: { color: 'rgba(255,255,255,0.28)', fontSize: 10, fontWeight: '600', letterSpacing: 0.5 },

  tabRow: {
    flexDirection: 'row',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.07)',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.07)',
    marginBottom: GRID_GAP,
  },
  tabBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderBottomWidth: 1.5,
    borderBottomColor: 'transparent',
  },
  tabLabel: { color: 'rgba(255,255,255,0.22)', fontSize: 12, fontWeight: '600' },

  grid: { flexDirection: 'row', gap: GRID_GAP, marginBottom: GRID_GAP },
  gridCell: { width: GRID_CELL_WIDTH },
  cell: {
    width: GRID_CELL_WIDTH,
    height: GRID_CELL_WIDTH * 1.25,
    overflow: 'hidden',
    backgroundColor: '#0D0D0D',
    position: 'relative',
  },
  cellAdd: {
    width: GRID_CELL_WIDTH,
    height: GRID_CELL_WIDTH * 1.25,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#080808',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  cellImg: { width: '100%', height: '100%' },
  cellGrad: { position: 'absolute', bottom: 0, left: 0, right: 0, height: '35%' },
  cellText: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 10, backgroundColor: '#0D0D0D' },
  cellCaption: { color: 'rgba(255,255,255,0.4)', fontSize: 10, textAlign: 'center', lineHeight: 15 },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContent: {
    width: '100%',
    maxWidth: 320,
    backgroundColor: 'rgba(30,30,30,0.98)',
    borderRadius: 16,
    padding: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  modalTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  modalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  modalItemText: { color: '#E5E7EB', fontSize: 15, fontWeight: '600' },
  modalItemDestructive: { marginTop: 4 },
  modalItemTextDestructive: { color: '#EF4444', fontSize: 15, fontWeight: '600' },

  empty: { paddingVertical: 56, alignItems: 'center', gap: 8, paddingHorizontal: 40 },
  emptyEmoji: { fontSize: 32, marginBottom: 2 },
  emptyTitle: { color: 'rgba(255,255,255,0.45)', fontSize: 15, fontWeight: '700' },
  emptySub: { color: 'rgba(255,255,255,0.22)', fontSize: 13, textAlign: 'center', lineHeight: 18 },
});
