import { StyleSheet } from 'react-native';

export const createStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000000' },
  progressBar: {
    height: 2,
    backgroundColor: 'rgba(167,139,250,0.15)',
    width: '100%',
  },
  progressFill: {
    height: 2,
    backgroundColor: '#A78BFA',
    borderRadius: 2,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.06)',
  },
  closeBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#0D0D0D',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
  },
  postBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 22,
    overflow: 'hidden',
    minWidth: 90,
    justifyContent: 'center',
  },
  postBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  scroll: { flex: 1 },
  imagePicker: {
    margin: 16,
    height: 320,
    borderRadius: 20,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    borderStyle: 'dashed',
  },
  previewImage: {
    ...StyleSheet.absoluteFillObject,
    resizeMode: 'cover',
  },
  imageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: 16,
  },
  changeImageText: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 13,
    fontWeight: '600',
  },
  videoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginBottom: 8,
  },
  videoBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  imagePickerTitle: {
    color: '#6B7280',
    fontSize: 16,
    fontWeight: '600',
  },
  imagePickerSub: {
    color: '#374151',
    fontSize: 13,
  },
  cameraBtn: {
    marginHorizontal: 16,
    marginBottom: 16,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: '#0D0D0D',
    alignItems: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  cameraBtnText: {
    color: '#9CA3AF',
    fontSize: 14,
    fontWeight: '600',
  },
  captionWrapper: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    gap: 12,
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  avatarSmall: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#7C3AED',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  avatarSmallText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  captionInput: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 16,
    lineHeight: 24,
    minHeight: 80,
  },
  charCount: {
    color: '#374151',
    fontSize: 12,
    textAlign: 'right',
    paddingRight: 16,
    marginBottom: 24,
  },
  tagsSection: { paddingHorizontal: 16 },
  tagsSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  tagsSectionTitle: {
    color: '#6B7280',
    fontSize: 13,
    fontWeight: '600',
  },
  tagsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  tagChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: '#0D0D0D',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  tagChipActive: {
    backgroundColor: 'rgba(167, 139, 250, 0.12)',
    borderColor: '#A78BFA',
  },
  tagChipText: {
    color: '#6B7280',
    fontSize: 13,
    fontWeight: '600',
  },
  tagChipTextActive: {
    color: '#A78BFA',
  },

  guildBanner: {
    marginHorizontal: 16,
    marginTop: 24,
    borderRadius: 16,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(167,139,250,0.2)',
  },
  guildBannerIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: 'rgba(167,139,250,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  guildBannerTitle: {
    color: '#C4B5FD',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 2,
  },
  guildBannerSub: {
    color: '#6B7280',
    fontSize: 11,
  },
});
